"""Converts TI's PSpice-style op-amp models into ngspice-ready copies.

TI originals live in models/ti_original/ and are never edited. The generated copies are written next
to this script in models/. Conversions (ngspice compat mode ltpsa still mishandles these):
  * S switches with a .MODEL VSWITCH  -> B-source with smooth log-conductance between VOFF and VON
  * G ... TABLE {expr} = (x,y)...     -> VALUE={pwl(expr, x,y, ...)}
  * R_NOISELESS resistor model        -> plain resistor (the model only zeroes thermal noise)

Usage: python3 prep_models.py
"""
import re
from pathlib import Path

MODEL_DIR = Path(__file__).resolve().parent / 'models'
SOURCES = {'OPA1656.LIB': 'opa1656.lib', 'OPAx188.LIB': 'opax188.lib'}
HEADER = '* GENERATED by sim/prep_models.py from TI original; do not edit. Switches -> B-sources, TABLE -> pwl.\n'

SWITCH_MODEL = re.compile(r'^\.MODEL\s+(\S+)\s+VSWITCH\s*\(?([^)\n]*)\)?\s*$', re.IGNORECASE | re.MULTILINE)
TABLE_SOURCE = re.compile(r'^(G\S*)\s+(\S+)\s+(\S+)\s+TABLE\s+\{(.+?)\}\s*=\s*\n((?:\+\([^\n]*\)\s*\n)+)',
                          re.IGNORECASE | re.MULTILINE)


def parse_params(text):
    return {key.upper(): value for key, value in re.findall(r'(\w+)\s*=\s*(\S+)', text)}


def convert_switches(text):
    models = {name: parse_params(params) for name, params in SWITCH_MODEL.findall(text)}
    text = SWITCH_MODEL.sub('', text)
    # S<name> n+ n- c+ c- <model>; ngspice has no PSpice VSWITCH here, so use a controlled conductance.
    switch = re.compile(r'^(S\S*)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s*$', re.MULTILINE)

    def replace(match):
        name, pos, neg, ctrl_pos, ctrl_neg, model = match.groups()
        params = models[model]
        ron, roff, von, voff = (params[key] for key in ('RON', 'ROFF', 'VON', 'VOFF'))
        # Smoothstep of the control voltage between VOFF and VON, interpolating log-conductance.
        fraction = f'max(0,min(1,(V({ctrl_pos},{ctrl_neg})-({voff}))/(({von})-({voff}))))'
        smooth = f'({fraction}*{fraction}*(3-2*{fraction}))'
        log_off, log_on = f'ln(1/({roff}))', f'ln(1/({ron}))'
        return (f'B{name} {pos} {neg} I=V({pos},{neg})*exp({log_off}+({log_on}-{log_off})*{smooth})')
    return switch.sub(replace, text)


def convert_tables(text):
    def replace(match):
        name, pos, neg, expr, rows = match.groups()
        points = re.findall(r'\+\(\s*([^,\s]+)\s*,\s*([^)\s]+)\s*\)', rows)
        flat = ', '.join(f'{x},{y}' for x, y in points)
        return f'{name} {pos} {neg} VALUE={{pwl({expr}, {flat})}}\n'
    return TABLE_SOURCE.sub(replace, text)


def drop_noiseless_model(text):
    text = re.sub(r'^\.MODEL\s+R_NOISELESS[^\n]*\n', '', text, flags=re.IGNORECASE | re.MULTILINE)
    return re.sub(r'^(R\S*\s+\S+\s+\S+)\s+R_NOISELESS\s+', r'\1 ', text, flags=re.IGNORECASE | re.MULTILINE)


def main():
    for source_name, output_name in SOURCES.items():
        text = (MODEL_DIR / 'ti_original' / source_name).read_text().replace('\r\n', '\n')
        text = drop_noiseless_model(convert_tables(convert_switches(text)))
        (MODEL_DIR / output_name).write_text(HEADER + text)
        print(f'{output_name}: written')


if __name__ == '__main__':
    main()
