"""
embed_web.py — PlatformIO pre-build script.

Reads every file listed in WEB_FILES from the data/ directory and writes
include/web_content.h, which embeds each file as a PROGMEM constant.

Text files are embedded as const char[] raw-string literals.
Files marked for gzip are compressed and embedded as const uint8_t[] byte
arrays, with a corresponding _len constant.  The firmware serves these with
a Content-Encoding: gzip header so the browser decompresses transparently.

Rebuild firmware after editing any file in data/ to pick up the changes.
"""

Import("env")  # noqa: F821  (PlatformIO injects this)

import gzip
import os

PROJECT_DIR  = env["PROJECT_DIR"]           # noqa: F821
DATA_DIR     = os.path.join(PROJECT_DIR, "data")
OUT_PATH     = os.path.join(PROJECT_DIR, "include", "web_content.h")

# (symbol_name, filename, use_gzip)
# When use_gzip is True the file is gzip-compressed and emitted as a byte
# array (uint8_t[]).  The firmware must serve it with Content-Encoding: gzip.
WEB_FILES = [
    ("index_html", "index.html", False),
    ("style_css",  "style.css",  False),
    ("app_js",     "app.js",     True),
    ("ota_html",   "ota.html",   False),
    ("ota_css",    "ota.css",    False),
    ("ota_js",     "ota.js",     False),
]

# Raw-string delimiter — must not appear inside any of the source files.
DELIM = "WEBFILE"

BYTES_PER_LINE = 16


def _emit_raw(h, sym, filename, src):
    """Embed a text file as a const char[] raw-string literal."""
    with open(src, "r", encoding="utf-8") as f:
        content = f.read()
    size = len(content.encode("utf-8"))
    h.write(f"// {filename}  ({size:,} bytes)\n")
    h.write(f'static const char {sym}[] PROGMEM = R"{DELIM}(\n')
    h.write(content)
    h.write(f'\n){DELIM}";\n\n')
    return size


def _emit_gzip(h, sym, filename, src):
    """Gzip-compress a file and embed as a const uint8_t[] byte array."""
    with open(src, "rb") as f:
        raw = f.read()
    compressed = gzip.compress(raw, compresslevel=9)
    raw_size = len(raw)
    gz_size  = len(compressed)
    ratio    = (1 - gz_size / raw_size) * 100 if raw_size > 0 else 0

    h.write(f"// {filename}  ({gz_size:,} bytes gzip, {raw_size:,} raw, {ratio:.0f}% smaller)\n")
    h.write(f"static const uint8_t {sym}_gz[] PROGMEM = {{\n")

    for i in range(0, gz_size, BYTES_PER_LINE):
        chunk = compressed[i : i + BYTES_PER_LINE]
        line  = ", ".join(f"0x{b:02x}" for b in chunk)
        comma = "," if i + BYTES_PER_LINE < gz_size else ""
        h.write(f"    {line}{comma}\n")

    h.write(f"}};\n")
    h.write(f"static const size_t {sym}_gz_len = sizeof({sym}_gz);\n\n")
    return gz_size


os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)

with open(OUT_PATH, "w", encoding="utf-8") as h:
    h.write("// Auto-generated by scripts/embed_web.py — do not edit.\n")
    h.write("// Edit the source files in data/ and rebuild to update.\n\n")
    h.write("#pragma once\n")
    h.write("#include <cstddef>   // size_t\n")
    h.write("#include <cstdint>   // uint8_t\n\n")

    for sym, filename, use_gzip in WEB_FILES:
        src = os.path.join(DATA_DIR, filename)
        if not os.path.exists(src):
            # Emit an empty placeholder so the symbol is always defined.
            # This keeps dashboard.cpp route handlers compiling correctly even
            # when the Vite build omits a file (e.g. style.css is not emitted
            # when using CSS-in-JS / Emotion, as with the Preact/MUI dashboard).
            print(f"[embed_web] INFO: {src} not found — emitting empty placeholder for '{sym}'")
            if use_gzip:
                h.write(f"// {filename}  (not found — empty gzip placeholder)\n")
                h.write(f"static const uint8_t {sym}_gz[] PROGMEM = {{}};\n")
                h.write(f"static const size_t {sym}_gz_len = 0;\n\n")
            else:
                h.write(f"// {filename}  (not found — empty placeholder)\n")
                h.write(f'static const char {sym}[] PROGMEM = "";\n\n')
            continue

        if use_gzip:
            sz = _emit_gzip(h, sym, filename, src)
            print(f"[embed_web] {filename} → {sym}_gz  ({sz:,} bytes gzip)")
        else:
            sz = _emit_raw(h, sym, filename, src)
            print(f"[embed_web] {filename} → {sym}  ({sz:,} bytes)")

print(f"[embed_web] Generated {OUT_PATH}")
