"""
embed_web.py — PlatformIO pre-build script.

Reads every file listed in WEB_FILES from the data/ directory and writes
include/web_content.h, which embeds each file as a PROGMEM const char[].

The firmware can then serve the content directly from flash without a
separate filesystem upload step or any LittleFS version dependencies.

Rebuild firmware after editing any file in data/ to pick up the changes.
"""

Import("env")  # noqa: F821  (PlatformIO injects this)

import os

PROJECT_DIR  = env["PROJECT_DIR"]           # noqa: F821
DATA_DIR     = os.path.join(PROJECT_DIR, "data")
OUT_PATH     = os.path.join(PROJECT_DIR, "include", "web_content.h")

# (symbol_name, filename) — add entries here for any new files in data/
WEB_FILES = [
    ("index_html", "index.html"),
    ("style_css",  "style.css"),
    ("app_js",     "app.js"),
]

# Raw-string delimiter — must not appear inside any of the source files.
DELIM = "WEBFILE"

os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)

with open(OUT_PATH, "w", encoding="utf-8") as h:
    h.write("// Auto-generated by scripts/embed_web.py — do not edit.\n")
    h.write("// Edit the source files in data/ and rebuild to update.\n\n")
    h.write("#pragma once\n\n")

    for sym, filename in WEB_FILES:
        src = os.path.join(DATA_DIR, filename)
        if not os.path.exists(src):
            print(f"[embed_web] WARNING: {src} not found, skipping")
            continue
        with open(src, "r", encoding="utf-8") as f:
            content = f.read()
        size = len(content.encode("utf-8"))
        h.write(f"// {filename}  ({size} bytes)\n")
        h.write(f'static const char {sym}[] PROGMEM = R"{DELIM}(\n')
        h.write(content)
        h.write(f'\n){DELIM}";\n\n')

print(f"[embed_web] Generated {OUT_PATH}")
