// Auto-generated by scripts/embed_web.py — do not edit.
// Edit the source files in data/ and rebuild to update.

#pragma once

// index.html  (505 bytes)
static const char index_html[] PROGMEM = R"WEBFILE(
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Cryocooler Dashboard</title>
  <link rel="stylesheet" href="/style.css">
</head>
<body>
  <h1>Cryocooler Dashboard</h1>
  <div id="status">Connecting&hellip;</div>
  <div id="controls">
    Auto-refresh: <input type="checkbox" id="autoRefresh" checked onchange="setRefresh()">
  </div>
  <div id="dash"></div>
  <script src="/app.js"></script>
</body>
</html>

)WEBFILE";

// style.css  (1231 bytes)
static const char style_css[] PROGMEM = R"WEBFILE(

body {
  font-family: monospace;
  background: #1a1a2e;
  color: #e0e0e0;
  margin: 0;
  padding: 20px;
}

h1 {
  color: #00d4ff;
  margin-bottom: 4px;
}

#status {
  font-size: .8em;
  color: #888;
  margin-bottom: 18px;
}

#controls {
  margin-bottom: 14px;
  font-size: .85em;
  color: #aaa;
}

#dash {
  display: grid;
  /*grid-template-columns: 1fr 1fr;*/
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 0 28px;
  align-items: start;   /* groups don't stretch to fill row height */
}

.group {
  margin-bottom: 18px;
}

.gt {
  color: #00d4ff;
  font-weight: bold;
  border-bottom: 1px solid #333;
  padding-bottom: 3px;
  margin-bottom: 6px;
  text-transform: uppercase;
  font-size: .8em;
  letter-spacing: 1px;
}

table {
  border-collapse: collapse;
  width: 100%;
}

td {
  padding: 3px 8px;
  border: 1px solid #2a2a4a;
  font-size: .88em;
  text-align: left;
}
td:empty::before {
  content: "empty";
  color: #8080805e;
  font-style: italic;
}

td.centered {
  text-align: center;
}

td:first-child {
  color: #aaa;
  text-align: right;
  width: 30%;
}

td:last-child {
  text-align: left;
  font-weight: bold;
}

.fault { color: #ff4444; }
.ready { color: #44cc44; }
.warn  { color: #ffaa00; }


)WEBFILE";

// app.js  (3202 bytes)
static const char app_js[] PROGMEM = R"WEBFILE(

const GROUP_ORDER = [
  'timestamp',
  'state',
  'cold_head',
  'dac',
  'rms',
  'relay',
  'indicator',
  'status',
  'cooling',
  'waveform',
  'system',
  'accelerometer',
  'firmware',
];



function groupOf(key) {
  const i = key.indexOf('.');
  return i > 0 ? key.slice(0, i) : key;
}

function fieldOf(key) {
  const i = key.indexOf('.');
  return i > 0 ? key.slice(i + 1) : key;
}

function cssClass(key, value) {
  if (key === 'indicator.fault' && value) return 'fault';
  if (key === 'indicator.ready' && value) return 'ready';
  if (key === 'relay.alarm'     && value) return 'warn';
  return '';
}

function setStatus(msg) {
  document.getElementById('status').textContent = msg;
}

function formatEpoch(value) {
  if (!value || value === 0) return `${value} (not synced)`;
  return `${value}<br/>${new Date(value * 1000).toUTCString()}`;
}

function objectToTable(obj) {
  return Object.entries(obj).map(([k,v])=>`<tr><td>${k}</td><td>${typeof v === 'object'
    ? objectToTable(v)
    : v}</td></tr>`).join('');
}

const overrides = {};

overrides['mod'] = (key, mods) => {

  let ret = `<table>
  <thead>
    <tr>
      <th>Service</th>
      <th>init</th>
      <th>service</th>
    </tr>
  </thead>
  <tbody>`;

  for(const [svc, svcStatus] of Object.entries(mods)){
    ret += `<tr><td>${svc}</td>`;

    for( const [svcName, svcVal] of Object.entries(svcStatus)){
      ret+= `<td class="centered">${svcVal}</td>`;
    }
    ret += `</tr>`;
  }
  ret += `</tbody></table>`

  return ret
}

async function refresh() {
  try {
    const data = await (await fetch('/api/telemetry')).json();

    // Group flat dot-notation keys by prefix
    const groups = {};
    for (const [key, value] of Object.entries(data)) {
      const g = groupOf(key);
      (groups[g] = groups[g] || []).push([key, value]);
    }

    const ordered = GROUP_ORDER.filter(g => groups[g]);
    const extra   = Object.keys(groups).filter(g => !GROUP_ORDER.includes(g));

    document.getElementById('dash').innerHTML = [...ordered, ...extra].map(g => {
      const rows = groups[g].map(([key, value]) => {
        if ( typeof overrides[key] === 'function'){
          return overrides[key](key, value);
        }

        //const display = key === 'timestamp' ? formatEpoch(value) : value;
        if ( typeof value === 'object'){
          return objectToTable(value)
        }

        return `<tr>
          <td>${fieldOf(key)}</td>
          <td class="${cssClass(key, value)}">${objectToTable(value)}</td>
        </tr>`;
      }).join('');
      return `<div class="group">
        <div class="gt">${g.replace(/_/g, ' ')}</div>
        <table>${rows}</table>
      </div>`;
    }).join('');

    setStatus('Updated: ' + new Date().toLocaleTimeString());
  } catch (e) {
    setStatus('Error: ' + e.message);
  }
}

let timer = null;

function setRefresh() {
  const checked = document.getElementById('autoRefresh').checked;
  clearInterval(timer);
  if (checked) {
    timer = setInterval(refresh, 1000);
    setStatus('Auto-refresh enabled');
  } else {
    timer = null;
    setStatus('Auto-refresh paused');
  }
}

// Initial load + start auto-refresh
refresh();
timer = setInterval(refresh, 1000);


)WEBFILE";

// ota.html  (1423 bytes)
static const char ota_html[] PROGMEM = R"WEBFILE(
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Firmware Update — Cryocooler</title>
  <link rel="stylesheet" href="/ota.css">
</head>
<body>
  <h2>Firmware Update</h2>
  <p class="sub">Upload a compiled <em>.bin</em> to flash the cryocooler controller over WiFi.</p>

  <div class="notice">
    <strong>&#9888; Safety notice:</strong> The system must be in
    <strong>Idle</strong> or <strong>Off</strong> state before uploading.
    A successful update reboots the MCU immediately — a running cryocooler
    will stop without a controlled shutdown ramp.
  </div>

  <form id="ota-form">
    <label>
      Firmware binary (.bin)
      <input type="file" id="file-input" name="firmware" accept=".bin" required>
    </label>
    <button type="submit" id="upload-btn">Upload &amp; Flash</button>
    <div id="progress-wrap">
      <progress id="progress-bar" value="0" max="100"></progress>
    </div>
    <div id="status"></div>
  </form>
  <div class="notice">
    <strong>FYI:</strong> This can be done via the CLI with:
    <p>
      <code>pio run -e esp32s3 &&
curl -vF "firmware=@.pio/build/esp32s3/firmware.bin" http://cryocooler.local/ota</code>
    </p>
    <p>Or, from the project root:</p>
    <p>
      <code>bash scripts/ota-update.sh</code>
    </p>
  </div>
  <script src="/ota.js"></script>
</body>
</html>

)WEBFILE";

// ota.css  (2070 bytes)
static const char ota_css[] PROGMEM = R"WEBFILE(
body {
  font-family: monospace;
  background: #1a1a2e;
  color: #e0e0e0;
  margin: 0;
  padding: 40px 20px;
  max-width: 620px;
  margin-right: 10%;
  margin-left: 10%;
}

h2 {
  color: #00d4ff;
  margin-bottom: 4px;
}

p.sub {
  color: #888;
  margin-top: 0;
  font-size: .85em;
}

.notice {
  background: #16213e;
  border-left: 3px solid #e74c3c;
  border-radius: 0 4px 4px 0;
  padding: 12px 16px;
  font-size: .85em;
  color: #aaa;
  margin: 20px 0;
  line-height: 1.5;
}

.notice strong {
  color: #e74c3c;
}

form {
  background: #16213e;
  border-radius: 6px;
  padding: 24px;
  margin-top: 8px;
}

label {
  display: block;
  font-size: .85em;
  color: #aaa;
  margin-bottom: 8px;
}

input[type="file"] {
  display: block;
  width: 100%;
  color: #e0e0e0;
  margin: 6px 0 20px;
  font-family: monospace;
  font-size: .9em;
}

button {
  background: #0f3460;
  color: #fff;
  border: none;
  padding: 10px 28px;
  border-radius: 4px;
  cursor: pointer;
  font-size: .95em;
  font-family: monospace;
  transition: background 0.15s;
}

button:hover:not(:disabled) {
  background: #1a5276;
}

button:disabled {
  opacity: 0.5;
  cursor: default;
}

#progress-wrap {
  display: none;
  margin-top: 16px;
}

progress {
  width: 100%;
  height: 8px;
  border-radius: 4px;
  border: none;
  background: #0d1b2a;
}

progress::-webkit-progress-bar   { background: #0d1b2a; border-radius: 4px; }
progress::-webkit-progress-value { background: #00d4ff; border-radius: 4px; }
progress::-moz-progress-bar      { background: #00d4ff; border-radius: 4px; }

#status {
  display: none;
  margin-top: 14px;
  padding: 10px 14px;
  border-radius: 4px;
  font-size: .88em;
}

#status.ok   { background: #1e8449; color: #fff; }
#status.err  { background: #922b21; color: #fff; }
#status.prog { background: #1a5276; color: #fff; }

code {
  display: block;
  padding: 5px;
  font-family: monospace, sans-serif;
  font-size: smaller;
  white-space: pre-wrap;
  word-wrap: break-word;
  overflow: auto;
  border: 1px solid #494949;
  border-radius: 4px;
  background-color: #27273a;
}
)WEBFILE";

// ota.js  (2173 bytes)
static const char ota_js[] PROGMEM = R"WEBFILE(
const form      = document.getElementById('ota-form');
const fileInput = document.getElementById('file-input');
const btn       = document.getElementById('upload-btn');
const statusEl  = document.getElementById('status');
const progWrap  = document.getElementById('progress-wrap');
const progBar   = document.getElementById('progress-bar');

const setStatus = (cls, msg) => {
  statusEl.className     = cls;
  statusEl.textContent   = msg;
  statusEl.style.display = 'block';
};

// Wrap XHR in a Promise so the upload can be awaited like fetch.
// XHR is kept specifically for upload progress events, which the fetch API
// does not expose.
const uploadFirmware = (file) => new Promise((resolve, reject) => {
  const xhr = new XMLHttpRequest();

  xhr.upload.addEventListener('progress', ({ loaded, total, lengthComputable }) => {
    if (lengthComputable) {
      progBar.value = Math.round((loaded / total) * 100);
    }
  });

  xhr.addEventListener('load', () => resolve({ status: xhr.status, text: xhr.responseText }));
  xhr.addEventListener('error', () => reject(new Error('network')));

  const fd = new FormData();
  fd.append('firmware', file);

  xhr.open('POST', '/ota');
  xhr.send(fd);
});

form.addEventListener('submit', async (e) => {
  e.preventDefault();

  const file = fileInput.files[0];
  if (!file) { alert('Select a .bin file first.'); return; }

  btn.disabled           = true;
  progWrap.style.display = 'block';
  progBar.value          = 0;
  setStatus('prog', `Uploading ${file.name} (${Math.round(file.size / 1024)} KB)\u2026`);

  try {
    const { status, text } = await uploadFirmware(file);

    progBar.value = 100;

    if (status === 200 && (text.startsWith('OK') || text.startsWith('Reboot'))) {
      setStatus('ok', text);
    } else {
      setStatus('err', text || `Upload failed (HTTP ${status})`);
      btn.disabled = false;
    }
  } catch {
    // XHR fires 'error' when the connection drops — which is exactly what
    // happens when a successful flash causes the board to reboot mid-response.
    progBar.value = 100;
    setStatus('ok', 'Upload complete. Board is rebooting \u2014 reconnect in ~10\u00a0s.');
  }
});

)WEBFILE";

