// Auto-generated by scripts/embed_web.py — do not edit.
// Edit the source files in data/ and rebuild to update.

#pragma once

// index.html  (505 bytes)
static const char k_index_html[] PROGMEM = R"WEBFILE(
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Cryocooler Dashboard</title>
  <link rel="stylesheet" href="/style.css">
</head>
<body>
  <h1>Cryocooler Dashboard</h1>
  <div id="status">Connecting&hellip;</div>
  <div id="controls">
    Auto-refresh: <input type="checkbox" id="autoRefresh" checked onchange="setRefresh()">
  </div>
  <div id="dash"></div>
  <script src="/app.js"></script>
</body>
</html>

)WEBFILE";

// style.css  (1107 bytes)
static const char k_style_css[] PROGMEM = R"WEBFILE(
body {
  font-family: monospace;
  background: #1a1a2e;
  color: #e0e0e0;
  margin: 0;
  padding: 20px;
}

h1 {
  color: #00d4ff;
  margin-bottom: 4px;
}

#status {
  font-size: .8em;
  color: #888;
  margin-bottom: 18px;
}

#controls {
  margin-bottom: 14px;
  font-size: .85em;
  color: #aaa;
}

#dash {
  display: grid;
  /*grid-template-columns: 1fr 1fr;*/
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 0 28px;
  align-items: start;   /* groups don't stretch to fill row height */
}

.group {
  margin-bottom: 18px;
}

.gt {
  color: #00d4ff;
  font-weight: bold;
  border-bottom: 1px solid #333;
  padding-bottom: 3px;
  margin-bottom: 6px;
  text-transform: uppercase;
  font-size: .8em;
  letter-spacing: 1px;
}

table {
  border-collapse: collapse;
  width: 100%;
}

td {
  padding: 3px 8px;
  border: 1px solid #2a2a4a;
  font-size: .88em;
  text-align: left;
}

td:first-child {
  color: #aaa;
  text-align: right;
  width: 30%;
}

td:last-child {
  text-align: left;
  font-weight: bold;
}

.fault { color: #ff4444; }
.ready { color: #44cc44; }
.warn  { color: #ffaa00; }

)WEBFILE";

// app.js  (2526 bytes)
static const char k_app_js[] PROGMEM = R"WEBFILE(
const GROUP_ORDER = [
  'state', 'cold_head', 'dac', 'rms', 'relay',
  'indicator', 'status', 'cooling', 'waveform', 'system', 'accel'
];

function groupOf(key) {
  const i = key.indexOf('.');
  return i > 0 ? key.slice(0, i) : key;
}

function fieldOf(key) {
  const i = key.indexOf('.');
  return i > 0 ? key.slice(i + 1) : key;
}

function cssClass(key, value) {
  if (key === 'indicator.fault' && value) return 'fault';
  if (key === 'indicator.ready' && value) return 'ready';
  if (key === 'relay.alarm'     && value) return 'warn';
  return '';
}

function setStatus(msg) {
  document.getElementById('status').textContent = msg;
}

function formatEpoch(value) {
  if (!value || value === 0) return `${value} (not synced)`;
  return `${value}<br/>${new Date(value * 1000).toUTCString()}`;
}

function objectToTable(obj) {
  return Object.entries(obj).map(([k,v])=>`<tr><td>${k}</td><td>${typeof v === 'object'
    ? objectToTable(v)
    : v}</td></tr>`).join('');
}

async function refresh() {
  try {
    const data = await (await fetch('/api/telemetry')).json();

    // Group flat dot-notation keys by prefix
    const groups = {};
    for (const [key, value] of Object.entries(data)) {
      const g = groupOf(key);
      (groups[g] = groups[g] || []).push([key, value]);
    }

    const ordered = GROUP_ORDER.filter(g => groups[g]);
    const extra   = Object.keys(groups).filter(g => !GROUP_ORDER.includes(g));

    document.getElementById('dash').innerHTML = [...ordered, ...extra].map(g => {
      const rows = groups[g].map(([key, value]) => {
        //const display = key === 'timestamp' ? formatEpoch(value) : value;
        return `<tr>
          <td>${fieldOf(key)}</td>
          <td class="${cssClass(key, value)}">${typeof value === 'object'
            ? objectToTable(value)
            : display}</td>
        </tr>`;
      }).join('');
      return `<div class="group">
        <div class="gt">${g.replace(/_/g, ' ')}</div>
        <table>${rows}</table>
      </div>`;
    }).join('');

    setStatus('Updated: ' + new Date().toLocaleTimeString());
  } catch (e) {
    setStatus('Error: ' + e.message);
  }
}

let timer = null;

function setRefresh() {
  const checked = document.getElementById('autoRefresh').checked;
  clearInterval(timer);
  if (checked) {
    timer = setInterval(refresh, 1000);
    setStatus('Auto-refresh enabled');
  } else {
    timer = null;
    setStatus('Auto-refresh paused');
  }
}

// Initial load + start auto-refresh
refresh();
timer = setInterval(refresh, 1000);

)WEBFILE";

